# name: reverse_text
# owner: ofge-gel_2019
# description: A simple Galaxy tool that reverses text
# homepage_url: https://github.com/ofge-gel_2019/reverse_text_tool
# remote_repository_url: https://github.com/ofge-gel_2019/reverse_text_tool
# type: unrestricted




name: reverse_text
description: "A simple Galaxy tool that reverses text"
owner: ofge-gel_2019
long_description: >
  A simple Galaxy tool that reverses text
categories:
  - Visualization